# Generated by Django 6.0.2 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_historialestadoinstrumento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='condicion',
            field=models.CharField(blank=True, choices=[('Excelente', 'Excelente'), ('Buena', 'Buena'), ('Regular', 'Regular'), ('Requiere Reparación', 'Requiere Reparación')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
